/**
 * Full default exercise library for coaches (seeded via prisma/seed.ts).
 * Categories match coach UI: strength | mobility | cardio | core | power | recovery.
 * Primary muscle group per slug lives in exercise-muscle-by-slug.ts (applied in seed).
 */
export type SeedExercise = {
  slug: string;
  name: string;
  category: "strength" | "mobility" | "cardio" | "core" | "power" | "recovery";
  equipment: string | null;
  cues: string;
};

export const exerciseSeedCatalog: SeedExercise[] = [
  // —— Recovery / breath / nervous system ——
  {
    slug: "box-breathing",
    name: "Box breathing",
    category: "recovery",
    equipment: null,
    cues: "Nasal inhale, soft exhale—let the exhale run longer when you need to downshift.",
  },
  {
    slug: "diaphragmatic-breathing",
    name: "Diaphragmatic breathing (360°)",
    category: "recovery",
    equipment: null,
    cues: "Hand on ribs; breathe so ribs expand laterally and back, not only the chest.",
  },
  {
    slug: "crocodile-breathing",
    name: "Crocodile breathing",
    category: "recovery",
    equipment: null,
    cues: "Prone, forehead on hands; feel low back rise gently with each inhale.",
  },
  {
    slug: "legs-up-the-wall",
    name: "Legs up the wall",
    category: "recovery",
    equipment: "Wall",
    cues: "Hips close to wall, arms relaxed; slow nasal breathing, jaw unclenched.",
  },
  {
    slug: "body-scan-relaxation",
    name: "Body scan (stillness)",
    category: "recovery",
    equipment: null,
    cues: "Notice contact points; exhale tension from jaw, neck, then shoulders.",
  },

  // —— Mobility / prep ——
  {
    slug: "cat-cow",
    name: "Cat–cow",
    category: "mobility",
    equipment: null,
    cues: "Move from pelvis; long spine in both directions, no rushing.",
  },
  {
    slug: "thoracic-rotation-quadruped",
    name: "Quadruped thoracic rotation",
    category: "mobility",
    equipment: null,
    cues: "Hand behind head, rotate through mid-back; hips stay quiet.",
  },
  {
    slug: "worlds-greatest-stretch",
    name: "World’s greatest stretch",
    category: "mobility",
    equipment: null,
    cues: "Lunge, elbow to floor, rotate open; breathe into the hip flexor side.",
  },
  {
    slug: "9090-hip-switch",
    name: "90/90 hip switch",
    category: "mobility",
    equipment: null,
    cues: "Keep both sit bones heavy; transition without hiking the hip.",
  },
  {
    slug: "pigeon-stretch",
    name: "Pigeon stretch",
    category: "mobility",
    equipment: null,
    cues: "Front shin angle you can hold; square hips, support front hip if needed.",
  },
  {
    slug: "couch-stretch",
    name: "Couch stretch (half-kneeling quad)",
    category: "mobility",
    equipment: "Bench or wall",
    cues: "Tuck pelvis, squeeze glute on back leg; ribs stacked.",
  },
  {
    slug: "band-pull-apart",
    name: "Band pull-apart",
    category: "mobility",
    equipment: "Resistance band",
    cues: "Soft elbows, pull to sternum height; pause, feel mid-back.",
  },
  {
    slug: "shoulder-cars",
    name: "Shoulder CARs (controlled articular)",
    category: "mobility",
    equipment: null,
    cues: "Biggest pain-free circle; opposite ribs stay down, no compensating.",
  },
  {
    slug: "ankle-mobility-wall",
    name: "Ankle dorsiflexion (wall knee tap)",
    category: "mobility",
    equipment: "Wall",
    cues: "Heel down, knee tracks over toes; keep arch from collapsing.",
  },
  {
    slug: "wrist-prep-circles",
    name: "Wrist circles / flexion extension",
    category: "mobility",
    equipment: null,
    cues: "Light tension; explore full range without sharp pain.",
  },

  // —— Dynamic warm-up ——
  {
    slug: "arm-circles",
    name: "Arm circles",
    category: "mobility",
    equipment: null,
    cues: "Gradually enlarge circles; switch directions.",
  },
  {
    slug: "leg-swings-sagittal",
    name: "Leg swings (front/back)",
    category: "mobility",
    equipment: "Support as needed",
    cues: "Tall posture; swing from hip, keep trunk quiet.",
  },
  {
    slug: "leg-swings-lateral",
    name: "Leg swings (lateral)",
    category: "mobility",
    equipment: "Support as needed",
    cues: "Face support; open hip without rotating torso.",
  },
  {
    slug: "inchworm",
    name: "Inchworm",
    category: "mobility",
    equipment: null,
    cues: "Walk hands out to plank, hips high walk feet in; hamstrings stay long.",
  },
  {
    slug: "high-knees",
    name: "High knees (march or run)",
    category: "cardio",
    equipment: null,
    cues: "Light feet, drive knee up; stay tall through crown of head.",
  },
  {
    slug: "butt-kicks",
    name: "Butt kicks",
    category: "cardio",
    equipment: null,
    cues: "Heels to glutes, quick turnover; avoid leaning back.",
  },
  {
    slug: "jumping-jacks",
    name: "Jumping jacks",
    category: "cardio",
    equipment: null,
    cues: "Soft landing through mid-foot; relaxed neck.",
  },
  {
    slug: "jump-rope",
    name: "Jump rope",
    category: "cardio",
    equipment: "Jump rope",
    cues: "Wrists turn rope; small hops, elbows in.",
  },

  // —— Cardio / conditioning ——
  {
    slug: "assault-bike",
    name: "Assault bike (fan bike)",
    category: "cardio",
    equipment: "Assault bike",
    cues: "Drive with legs first; steady breathing, relaxed grip.",
  },
  {
    slug: "rowing-machine",
    name: "Rowing machine",
    category: "cardio",
    equipment: "Rower",
    cues: "Legs–body–arms on drive; arms–body–legs on return.",
  },
  {
    slug: "ski-erg",
    name: "Ski erg",
    category: "cardio",
    equipment: "Ski erg",
    cues: "Hinge from hips, straight arms pull past hips; rhythmic cadence.",
  },
  {
    slug: "treadmill-run",
    name: "Treadmill run / jog",
    category: "cardio",
    equipment: "Treadmill",
    cues: "Quiet feet, slight forward lean from ankles, relaxed shoulders.",
  },
  {
    slug: "spin-bike",
    name: "Spin / assault-style bike (seated)",
    category: "cardio",
    equipment: "Bike",
    cues: "Knee soft at bottom dead spot; core engaged, not collapsing on bars.",
  },
  {
    slug: "versa-climber",
    name: "VersaClimber",
    category: "cardio",
    equipment: "VersaClimber",
    cues: "Short stride to start; hips and shoulders stay square.",
  },
  {
    slug: "burpee",
    name: "Burpee",
    category: "cardio",
    equipment: null,
    cues: "Plank is solid; land with knees tracking, optional jump at top.",
  },
  {
    slug: "mountain-climber",
    name: "Mountain climber",
    category: "cardio",
    equipment: null,
    cues: "Hands under shoulders; drive knee toward chest without piking hips.",
  },
  {
    slug: "battle-ropes-alternating",
    name: "Battle ropes (alternating waves)",
    category: "cardio",
    equipment: "Battle ropes",
    cues: "Athletic stance; move from shoulders, ribs down.",
  },

  // —— Squat & knee-dominant ——
  {
    slug: "goblet-squat",
    name: "Goblet squat",
    category: "strength",
    equipment: "Kettlebell or dumbbell",
    cues: "Elbows inside knees at bottom, ribs over pelvis, drive the floor away.",
  },
  {
    slug: "back-squat-high-bar",
    name: "Back squat (high bar)",
    category: "strength",
    equipment: "Barbell, rack",
    cues: "Brace 360°, sit between hips; knees track toes, depth you own.",
  },
  {
    slug: "back-squat-low-bar",
    name: "Back squat (low bar)",
    category: "strength",
    equipment: "Barbell, rack",
    cues: "More hinge flavor; bar pinned to rear delts, consistent bar path.",
  },
  {
    slug: "front-squat",
    name: "Front squat",
    category: "strength",
    equipment: "Barbell, rack",
    cues: "Elbows high, torso tall; full foot pressure, knees out in hole.",
  },
  {
    slug: "zercher-squat",
    name: "Zercher squat",
    category: "strength",
    equipment: "Barbell",
    cues: "Bar in elbow crook; brace hard, sit tall through mid-back.",
  },
  {
    slug: "safety-bar-squat",
    name: "Safety bar squat",
    category: "strength",
    equipment: "SSB, rack",
    cues: "Let the camber dictate torso angle; still stack ribs over hips.",
  },
  {
    slug: "leg-press",
    name: "Leg press",
    category: "strength",
    equipment: "Leg press",
    cues: "Full foot on sled; no lockout bounce; low back stays glued to pad.",
  },
  {
    slug: "hack-squat",
    name: "Hack squat",
    category: "strength",
    equipment: "Hack squat",
    cues: "Knees follow foot angle; control depth, no tailbone tuck at bottom.",
  },
  {
    slug: "bulgarian-split-squat",
    name: "Bulgarian split squat",
    category: "strength",
    equipment: "Dumbbells, bench",
    cues: "Torso slight forward lean; front knee tracks, rear hip extends.",
  },
  {
    slug: "reverse-lunge",
    name: "Reverse lunge",
    category: "strength",
    equipment: "Dumbbells optional",
    cues: "Step back softly; front heel planted, stand through front leg.",
  },
  {
    slug: "forward-lunge",
    name: "Forward lunge",
    category: "strength",
    equipment: "Dumbbells optional",
    cues: "Short step if knee sensitive; vertical shin on front leg if possible.",
  },
  {
    slug: "walking-lunge",
    name: "Walking lunge",
    category: "strength",
    equipment: "Dumbbells optional",
    cues: "Tall torso; control the knee line, don’t let front knee cave.",
  },
  {
    slug: "step-up",
    name: "Step-up",
    category: "strength",
    equipment: "Box, dumbbells optional",
    cues: "Drive through top heel; don’t push off the back leg.",
  },
  {
    slug: "cossack-squat",
    name: "Cossack squat",
    category: "strength",
    equipment: null,
    cues: "Heel down on working leg; other leg stays long—mobility + strength.",
  },
  {
    slug: "wall-sit",
    name: "Wall sit (isometric)",
    category: "strength",
    equipment: "Wall",
    cues: "Thighs parallel if tolerable; breathe steady, ribs down.",
  },

  // —— Hip hinge ——
  {
    slug: "barbell-deadlift",
    name: "Barbell deadlift (conventional)",
    category: "strength",
    equipment: "Barbell",
    cues: "Bar over mid-foot; push floor away, stand tall with glutes at lockout.",
  },
  {
    slug: "sumo-deadlift",
    name: "Sumo deadlift",
    category: "strength",
    equipment: "Barbell",
    cues: "Spread the floor; chest over bar to start, wedge hips to bar.",
  },
  {
    slug: "trap-bar-deadlift",
    name: "Trap bar deadlift",
    category: "strength",
    equipment: "Trap bar",
    cues: "Handles center of foot; sit hips and stand like a squat-hinge blend.",
  },
  {
    slug: "romanian-deadlift-barbell",
    name: "Romanian deadlift (barbell)",
    category: "strength",
    equipment: "Barbell",
    cues: "Soft knee bend fixed; hips go back, bar skims legs, feel hamstrings.",
  },
  {
    slug: "romanian-deadlift-dumbbell",
    name: "Romanian deadlift (dumbbells)",
    category: "strength",
    equipment: "Dumbbells",
    cues: "Same hinge rules; dumbbells close to legs.",
  },
  {
    slug: "single-leg-rdl",
    name: "Single-leg RDL",
    category: "strength",
    equipment: "Dumbbell or kettlebell",
    cues: "Hip square to floor; slight knee bend, long spine, reach leg back.",
  },
  {
    slug: "good-morning",
    name: "Good morning",
    category: "strength",
    equipment: "Barbell or safety bar",
    cues: "Hinge only—no squat; bar stays over mid-foot, brace hard.",
  },
  {
    slug: "hip-thrust-barbell",
    name: "Barbell hip thrust",
    category: "strength",
    equipment: "Barbell, bench",
    cues: "Chin tucked, ribs down; vertical shins at top, squeeze glutes not low back.",
  },
  {
    slug: "glute-bridge",
    name: "Glute bridge",
    category: "strength",
    equipment: null,
    cues: "Posterior pelvic tilt at top; don’t arch through ribs.",
  },
  {
    slug: "single-leg-glute-bridge",
    name: "Single-leg glute bridge",
    category: "strength",
    equipment: null,
    cues: "Keep hips level; drive through heel, no cramping in hamstring—adjust range.",
  },
  {
    slug: "kettlebell-swing",
    name: "Kettlebell swing",
    category: "power",
    equipment: "Kettlebell",
    cues: "Hinge power, arms are ropes; float to chest height unless hardstyle.",
  },
  {
    slug: "cable-pull-through",
    name: "Cable pull-through",
    category: "strength",
    equipment: "Cable low",
    cues: "Rope between legs, hinge hips back, stand tall squeezing glutes.",
  },

  // —— Horizontal push ——
  {
    slug: "barbell-bench-press",
    name: "Barbell bench press",
    category: "strength",
    equipment: "Barbell, bench",
    cues: "Leg drive, slight arch, bar path J-curve to low chest.",
  },
  {
    slug: "dumbbell-bench-press",
    name: "Dumbbell bench press",
    category: "strength",
    equipment: "Dumbbells, bench",
    cues: "Wrists stacked; control bottom, don’t flare elbows excessively.",
  },
  {
    slug: "incline-dumbbell-press",
    name: "Incline dumbbell press",
    category: "strength",
    equipment: "Dumbbells, bench",
    cues: "Elbows under wrists at bottom; press slightly back toward rack.",
  },
  {
    slug: "push-up",
    name: "Push-up",
    category: "strength",
    equipment: null,
    cues: "Body line from head to heel; full chest range, protract at top.",
  },
  {
    slug: "incline-push-up",
    name: "Incline push-up",
    category: "strength",
    equipment: "Bench or bar",
    cues: "Same plank quality; easier angle for volume or rehab.",
  },
  {
    slug: "floor-press-dumbbell",
    name: "Dumbbell floor press",
    category: "strength",
    equipment: "Dumbbells",
    cues: "Upper arms rest briefly on floor; triceps finish lockout.",
  },
  {
    slug: "cable-fly",
    name: "Cable fly (high to low or mid)",
    category: "strength",
    equipment: "Cable",
    cues: "Soft elbows fixed angle; hug the tree, squeeze sternum.",
  },

  // —— Vertical / shoulder push ——
  {
    slug: "strict-press-barbell",
    name: "Strict press (standing barbell)",
    category: "strength",
    equipment: "Barbell",
    cues: "Glutes and quads on; bar path vertical, head through at top.",
  },
  {
    slug: "half-kneeling-press",
    name: "Half-kneeling press",
    category: "strength",
    equipment: "Dumbbells",
    cues: "Glute on down knee on; press without flaring ribs.",
  },
  {
    slug: "dumbbell-shoulder-press-seated",
    name: "Seated dumbbell shoulder press",
    category: "strength",
    equipment: "Dumbbells, bench",
    cues: "Back supported or not—either way, ribs down, full lockout.",
  },
  {
    slug: "landmine-press",
    name: "Landmine press",
    category: "strength",
    equipment: "Landmine",
    cues: "Arc the bar; stack wrist over elbow, stand tall.",
  },
  {
    slug: "arnold-press",
    name: "Arnold press",
    category: "strength",
    equipment: "Dumbbells",
    cues: "Rotate palms out as you press; no low-back arch.",
  },
  {
    slug: "pike-push-up",
    name: "Pike push-up",
    category: "strength",
    equipment: null,
    cues: "Hips high, head toward floor; shoulder line, not nose dive.",
  },
  {
    slug: "lateral-raise",
    name: "Lateral raise",
    category: "strength",
    equipment: "Dumbbells or cables",
    cues: "Slight lean forward; lead with elbows, stop below painful range.",
  },
  {
    slug: "rear-delt-fly",
    name: "Rear delt fly (bend-over)",
    category: "strength",
    equipment: "Dumbbells",
    cues: "Soft elbows, thumbs down or neutral; squeeze shoulder blades.",
  },

  // —— Pull ——
  {
    slug: "pendlay-row",
    name: "Pendlay row",
    category: "strength",
    equipment: "Barbell",
    cues: "Parallel torso each rep; explode to sternum, no hip rise.",
  },
  {
    slug: "bent-over-row-barbell",
    name: "Bent-over row (barbell)",
    category: "strength",
    equipment: "Barbell",
    cues: "Hinge holds; pull to lower ribs, squeeze mid-back.",
  },
  {
    slug: "single-arm-dumbbell-row",
    name: "Single-arm dumbbell row",
    category: "strength",
    equipment: "Dumbbell, bench",
    cues: "Shoulder down away from ear; pull elbow to hip pocket.",
  },
  {
    slug: "seated-cable-row",
    name: "Seated cable row",
    category: "strength",
    equipment: "Cable",
    cues: "Stack torso over hips; finish with shoulder blades, not neck.",
  },
  {
    slug: "chest-supported-row",
    name: "Chest-supported row",
    category: "strength",
    equipment: "Incline bench, dumbbells",
    cues: "No momentum; pull elbows back, thumbs optional toward hips.",
  },
  {
    slug: "inverted-row",
    name: "Inverted row",
    category: "strength",
    equipment: "Bar or rings",
    cues: "Body line tight; pull chest to bar, protract at bottom.",
  },
  {
    slug: "face-pull",
    name: "Face pull",
    category: "strength",
    equipment: "Cable, rope",
    cues: "Elbows high, pull to face/nose; external rotate at end range.",
  },
  {
    slug: "pull-up",
    name: "Pull-up",
    category: "strength",
    equipment: "Pull-up bar",
    cues: "Depress shoulders first; chest to bar intention, controlled lower.",
  },
  {
    slug: "chin-up",
    name: "Chin-up",
    category: "strength",
    equipment: "Pull-up bar",
    cues: "Supinated grip; same control, slightly more biceps.",
  },
  {
    slug: "lat-pulldown-wide",
    name: "Lat pulldown (wide grip)",
    category: "strength",
    equipment: "Cable machine",
    cues: "Lean slightly, pull elbows to pockets; no yanking with low back.",
  },
  {
    slug: "assisted-pull-up",
    name: "Assisted pull-up (band or machine)",
    category: "strength",
    equipment: "Band or assist machine",
    cues: "Same pattern as strict pull-up; reduce assist over time.",
  },

  // —— Arms ——
  {
    slug: "barbell-curl",
    name: "Barbell curl",
    category: "strength",
    equipment: "Barbell or EZ bar",
    cues: "Elbows pinned; no hip swing unless programmed cheat reps.",
  },
  {
    slug: "hammer-curl",
    name: "Hammer curl",
    category: "strength",
    equipment: "Dumbbells",
    cues: "Neutral grip; supinate slightly at top optional.",
  },
  {
    slug: "tricep-pushdown-rope",
    name: "Tricep pushdown (rope)",
    category: "strength",
    equipment: "Cable",
    cues: "Elbows fixed to ribs; split rope at bottom, long head stretch at top.",
  },
  {
    slug: "skull-crusher-ez",
    name: "Skull crusher (EZ bar)",
    category: "strength",
    equipment: "EZ bar, bench",
    cues: "Hinge at elbows only; bar clears forehead, strong lockout.",
  },
  {
    slug: "overhead-tricep-extension-cable",
    name: "Overhead tricep extension (cable or DB)",
    category: "strength",
    equipment: "Cable or dumbbell",
    cues: "Biceps by ears, ribs down; only forearms move.",
  },

  // —— Core ——
  {
    slug: "dead-bug",
    name: "Dead bug",
    category: "core",
    equipment: null,
    cues: "Low back glued to floor; exhale as limb extends, opposite arm/leg.",
  },
  {
    slug: "bird-dog",
    name: "Bird dog",
    category: "core",
    equipment: null,
    cues: "Hip square; long line from heel to hand, no rotation.",
  },
  {
    slug: "front-plank",
    name: "Front plank",
    category: "core",
    equipment: null,
    cues: "Ribs tucked, glutes on; breathe behind the brace.",
  },
  {
    slug: "side-plank",
    name: "Side plank",
    category: "core",
    equipment: null,
    cues: "Elbow under shoulder; stack hips, top hip forward.",
  },
  {
    slug: "hollow-body-hold",
    name: "Hollow body hold",
    category: "core",
    equipment: null,
    cues: "Low back pressed to floor; legs and shoulders off ground you can hold.",
  },
  {
    slug: "pallof-press",
    name: "Pallof press",
    category: "core",
    equipment: "Cable or band",
    cues: "Stand perpendicular; hands at sternum, extend without twisting.",
  },
  {
    slug: "hanging-knee-raise",
    name: "Hanging knee raise",
    category: "core",
    equipment: "Pull-up bar",
    cues: "Posterior pelvic tilt to start; control swing, exhale on lift.",
  },
  {
    slug: "ab-wheel-rollout",
    name: "Ab wheel rollout",
    category: "core",
    equipment: "Ab wheel",
    cues: "Hips extended, only go as far as you can recover without low-back fold.",
  },
  {
    slug: "cable-crunch",
    name: "Cable crunch (kneeling)",
    category: "core",
    equipment: "Cable",
    cues: "Spinal flexion from thoracic; hips stay high, don’t sit back.",
  },

  // —— Power / plyo / Olympic-style ——
  {
    slug: "box-jump",
    name: "Box jump",
    category: "power",
    equipment: "Plyo box",
    cues: "Soft landing with full foot; stand tall at top, step down if fatigued.",
  },
  {
    slug: "broad-jump",
    name: "Broad jump",
    category: "power",
    equipment: null,
    cues: "Swing arms, hip extension; stick landing with knees tracking.",
  },
  {
    slug: "med-ball-slam",
    name: "Medicine ball slam",
    category: "power",
    equipment: "Medicine ball",
    cues: "Hinge then explode down; ball doesn’t bounce into face.",
  },
  {
    slug: "kettlebell-clean",
    name: "Kettlebell clean (single)",
    category: "power",
    equipment: "Kettlebell",
    cues: "Hike, zip up; bell floats to rack without banging forearm.",
  },
  {
    slug: "dumbbell-snatch-single",
    name: "Single dumbbell snatch",
    category: "power",
    equipment: "Dumbbell",
    cues: "Close arc; punch to lockout, receive with soft knee.",
  },
  {
    slug: "power-clean",
    name: "Power clean (from floor or hang)",
    category: "power",
    equipment: "Barbell",
    cues: "Jump shrug under bar; elbows high and outside in catch.",
  },
  {
    slug: "push-press",
    name: "Push press",
    category: "power",
    equipment: "Barbell or dumbbells",
    cues: "Dip straight down, drive hard; finish overhead stacked.",
  },
  {
    slug: "push-jerk",
    name: "Push jerk",
    category: "power",
    equipment: "Barbell",
    cues: "Dip and drive, quick drop under bar; lockout wide and stable.",
  },

  // —— Carries / loaded stability ——
  {
    slug: "farmer-carry",
    name: "Carry (farmer or suitcase)",
    category: "strength",
    equipment: "Kettlebells or dumbbells",
    cues: "Tall ribs, shoulders back and down, short steps if needed to stay stacked.",
  },
  {
    slug: "rack-carry",
    name: "Rack carry (KB or DB)",
    category: "strength",
    equipment: "Kettlebells or dumbbells",
    cues: "Elbows connected to ribs; breathe behind brace, walk tall.",
  },
  {
    slug: "overhead-carry",
    name: "Overhead carry",
    category: "strength",
    equipment: "Dumbbell, kettlebell, or plate",
    cues: "Wrist stacked over shoulder; ribs down, biceps by ear.",
  },
  {
    slug: "suitcase-carry",
    name: "Suitcase carry (single-side)",
    category: "strength",
    equipment: "Dumbbell or kettlebell",
    cues: "Don’t lean into the weight; stay level, feel obliques.",
  },
];
