import type { MuscleGroup } from "../lib/muscle-groups";

/** Primary muscle group per seeded exercise slug (must cover every entry in exercise-seed-catalog). */
export const exerciseMuscleBySlug: Record<string, MuscleGroup> = {
  "box-breathing": "recovery",
  "diaphragmatic-breathing": "recovery",
  "crocodile-breathing": "recovery",
  "legs-up-the-wall": "recovery",
  "body-scan-relaxation": "recovery",

  "cat-cow": "mobility",
  "thoracic-rotation-quadruped": "mobility",
  "worlds-greatest-stretch": "mobility",
  "9090-hip-switch": "mobility",
  "pigeon-stretch": "glutes",
  "couch-stretch": "quadriceps",
  "band-pull-apart": "back",
  "shoulder-cars": "shoulders",
  "ankle-mobility-wall": "calves",
  "wrist-prep-circles": "forearms",

  "arm-circles": "shoulders",
  "leg-swings-sagittal": "hamstrings",
  "leg-swings-lateral": "glutes",
  "inchworm": "full_body",

  "high-knees": "cardio",
  "butt-kicks": "hamstrings",
  "jumping-jacks": "cardio",
  "jump-rope": "cardio",

  "assault-bike": "cardio",
  "rowing-machine": "back",
  "ski-erg": "back",
  "treadmill-run": "cardio",
  "spin-bike": "cardio",
  "versa-climber": "cardio",
  "burpee": "full_body",
  "mountain-climber": "core",
  "battle-ropes-alternating": "shoulders",

  "goblet-squat": "quadriceps",
  "back-squat-high-bar": "quadriceps",
  "back-squat-low-bar": "quadriceps",
  "front-squat": "quadriceps",
  "zercher-squat": "quadriceps",
  "safety-bar-squat": "quadriceps",
  "leg-press": "quadriceps",
  "hack-squat": "quadriceps",
  "bulgarian-split-squat": "quadriceps",
  "reverse-lunge": "quadriceps",
  "forward-lunge": "quadriceps",
  "walking-lunge": "quadriceps",
  "step-up": "quadriceps",
  "cossack-squat": "mobility",
  "wall-sit": "quadriceps",

  "barbell-deadlift": "hamstrings",
  "sumo-deadlift": "hamstrings",
  "trap-bar-deadlift": "hamstrings",
  "romanian-deadlift-barbell": "hamstrings",
  "romanian-deadlift-dumbbell": "hamstrings",
  "single-leg-rdl": "hamstrings",
  "good-morning": "hamstrings",
  "hip-thrust-barbell": "glutes",
  "glute-bridge": "glutes",
  "single-leg-glute-bridge": "glutes",
  "kettlebell-swing": "glutes",
  "cable-pull-through": "glutes",

  "barbell-bench-press": "chest",
  "dumbbell-bench-press": "chest",
  "incline-dumbbell-press": "chest",
  "push-up": "chest",
  "incline-push-up": "chest",
  "floor-press-dumbbell": "chest",
  "cable-fly": "chest",

  "strict-press-barbell": "shoulders",
  "half-kneeling-press": "shoulders",
  "dumbbell-shoulder-press-seated": "shoulders",
  "landmine-press": "shoulders",
  "arnold-press": "shoulders",
  "pike-push-up": "shoulders",
  "lateral-raise": "shoulders",
  "rear-delt-fly": "shoulders",

  "pendlay-row": "back",
  "bent-over-row-barbell": "back",
  "single-arm-dumbbell-row": "back",
  "seated-cable-row": "back",
  "chest-supported-row": "back",
  "inverted-row": "back",
  "face-pull": "shoulders",
  "pull-up": "back",
  "chin-up": "back",
  "lat-pulldown-wide": "back",
  "assisted-pull-up": "back",

  "barbell-curl": "biceps",
  "hammer-curl": "biceps",
  "tricep-pushdown-rope": "triceps",
  "skull-crusher-ez": "triceps",
  "overhead-tricep-extension-cable": "triceps",

  "dead-bug": "core",
  "bird-dog": "core",
  "front-plank": "core",
  "side-plank": "core",
  "hollow-body-hold": "core",
  "pallof-press": "core",
  "hanging-knee-raise": "core",
  "ab-wheel-rollout": "core",
  "cable-crunch": "core",

  "box-jump": "quadriceps",
  "broad-jump": "quadriceps",
  "med-ball-slam": "core",
  "kettlebell-clean": "full_body",
  "dumbbell-snatch-single": "full_body",
  "power-clean": "full_body",
  "push-press": "shoulders",
  "push-jerk": "shoulders",

  "farmer-carry": "full_body",
  "rack-carry": "shoulders",
  "overhead-carry": "shoulders",
  "suitcase-carry": "core",
};
